/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleCpp.js
 */

#include "rn77JSI.h"

namespace facebook::react {

static jsi::Value __hostFunction_NativeRn77CxxSpecJSI_multiply(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeRn77CxxSpecJSI *>(&turboModule)->multiply(
    rt,
    count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asNumber(),
    count <= 1 ? throw jsi::JSError(rt, "Expected argument in position 1 to be passed") : args[1].asNumber()
  );
}
static jsi::Value __hostFunction_NativeRn77CxxSpecJSI_hello(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  return static_cast<NativeRn77CxxSpecJSI *>(&turboModule)->hello(
    rt,
    count <= 0 ? throw jsi::JSError(rt, "Expected argument in position 0 to be passed") : args[0].asString(rt)
  );
}

NativeRn77CxxSpecJSI::NativeRn77CxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker)
  : TurboModule("Rn77Cxx", jsInvoker) {
  methodMap_["multiply"] = MethodMetadata {2, __hostFunction_NativeRn77CxxSpecJSI_multiply};
  methodMap_["hello"] = MethodMetadata {1, __hostFunction_NativeRn77CxxSpecJSI_hello};
}


} // namespace facebook::react
